#!/bin/sh
#
# Xcode Cloud pre-xcodebuild hook.
#
# PURPOSE
#   Derive the bundle build number from Xcode Cloud's own build counter instead
#   of a constant committed to the repository. A committed constant only ever
#   advances when somebody remembers to edit it, so every upload after the first
#   is rejected with "The bundle version must be higher than the previously
#   uploaded version" until a human intervenes.
#
# CONTRACT (Apple, "Writing custom build scripts" + "Environment variable
# reference"; both read 2026-08-07)
#   - The file must be named exactly ci_pre_xcodebuild.sh and sit at the TOP
#     LEVEL of a directory named ci_scripts that is located in the same
#     directory as the Xcode project. Prism.xcodeproj is at the repository
#     root, so ci_scripts/ is at the repository root.
#   - The file must be executable AND carry a shebang. Apple: "If you don't
#     include a shebang as the first line of your custom script or forget to
#     make the file executable, Xcode Cloud runs the script as `zsh $filename`,
#     which -- depending on your script -- can cause a failing build."
#   - Xcode Cloud "runs your custom build scripts with this directory as the
#     root directory", i.e. the working directory is ci_scripts/, NOT the
#     repository root. Nothing below is resolved relative to "." for that
#     reason.
#   - CI_BUILD_NUMBER is "The number of the current build" and is listed under
#     "Variables that are always available". It is absent outside Xcode Cloud.
#   - CI_PRIMARY_REPOSITORY_PATH is "The location of the source code in the
#     temporary build environment cloned from the primary repository specified
#     in the workflow", also always available.
#   - sudo is not available to custom build scripts.
#
# WHY THIS WRITES project.yml AND Prism.xcodeproj/project.pbxproj
#   Prism.xcodeproj is GENERATED by XcodeGen from project.yml, and is also
#   committed. Xcode Cloud does not run xcodegen -- there is no
#   ci_post_clone.sh -- so xcodebuild reads the committed pbxproj, and that is
#   the file which decides this build's version. project.yml is written as
#   well so the two representations cannot disagree if an xcodegen post-clone
#   step is ever added. Both writes land in the ephemeral build clone and are
#   never committed.
#
# WHY NOT agvtool, PlistBuddy, OR A DIRECT Info.plist WRITE
#   App/Info.plist and Widget/Info.plist are both generated by XcodeGen from
#   the `info:` blocks in project.yml, so a write to either is discarded the
#   next time anyone runs xcodegen. Beyond that, neither is the source of the
#   value: the app target sets GENERATE_INFOPLIST_FILE=YES and takes
#   CFBundleVersion from CURRENT_PROJECT_VERSION, and the widget's committed
#   plist holds the literal string "$(CURRENT_PROJECT_VERSION)". One build
#   setting feeds both targets, which is what keeps the widget extension's
#   build number equal to its host app's -- they cannot drift apart, because
#   there is only one value.
#
# LOCAL ARCHIVES
#   scripts/archive-testflight.sh runs `xcodegen generate` and archives without
#   Xcode Cloud, so CI_BUILD_NUMBER is unset there. In that case this script
#   writes NOTHING and exits 0, leaving the committed CURRENT_PROJECT_VERSION
#   as the floor. It does not substitute a default, because a default would be
#   a build number nobody chose.

set -eu

log() { echo "[ci_pre_xcodebuild] $*"; }

# ---------------------------------------------------------------------------
# Outcome 1 of 3: not an Xcode Cloud build. Touch nothing.
# ---------------------------------------------------------------------------
if [ -z "${CI_BUILD_NUMBER:-}" ]; then
  log "CI_BUILD_NUMBER is unset or empty; this is not an Xcode Cloud build."
  log "SKIP: leaving the committed CURRENT_PROJECT_VERSION untouched."
  exit 0
fi

# ---------------------------------------------------------------------------
# Outcome 2 of 3: present but unusable. Refuse loudly rather than write junk.
# Apple: build numbers "are always integers"; hashes, timestamps and other
# strings are not accepted.
# ---------------------------------------------------------------------------
case "$CI_BUILD_NUMBER" in
  0|0*|*[!0-9]*)
    log "REFUSE: CI_BUILD_NUMBER='$CI_BUILD_NUMBER' is not a positive integer"
    log "        without leading zeros. Xcode Cloud build numbers are integers."
    exit 1
    ;;
esac

BUILD_NUMBER="$CI_BUILD_NUMBER"

# ---------------------------------------------------------------------------
# Resolve the repository root by EFFECT, and say which candidate answered.
# This is a lookup, not a claim: each candidate is tested by whether the
# project file is actually readable there, so a wrong answer is impossible
# rather than merely unlikely. If none answers, refuse.
# ---------------------------------------------------------------------------
SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=''
REPO_ROOT_SOURCE=''

for candidate_pair in \
  "CI_PRIMARY_REPOSITORY_PATH:${CI_PRIMARY_REPOSITORY_PATH:-}" \
  "ci_scripts_parent:${SCRIPT_DIR}/.." \
  "cwd_parent:$(pwd)/.."
do
  candidate_name=${candidate_pair%%:*}
  candidate_path=${candidate_pair#*:}
  [ -n "$candidate_path" ] || continue
  [ -f "${candidate_path}/Prism.xcodeproj/project.pbxproj" ] || continue
  REPO_ROOT=$(CDPATH='' cd -- "$candidate_path" && pwd)
  REPO_ROOT_SOURCE="$candidate_name"
  break
done

if [ -z "$REPO_ROOT" ]; then
  log "REFUSE: could not locate Prism.xcodeproj/project.pbxproj from any of"
  log "        CI_PRIMARY_REPOSITORY_PATH='${CI_PRIMARY_REPOSITORY_PATH:-}',"
  log "        '${SCRIPT_DIR}/..', or '$(pwd)/..'."
  exit 1
fi

log "build number   : $BUILD_NUMBER (from CI_BUILD_NUMBER)"
log "repository root: $REPO_ROOT (resolved via $REPO_ROOT_SOURCE)"

PBXPROJ="${REPO_ROOT}/Prism.xcodeproj/project.pbxproj"
PROJECT_YML="${REPO_ROOT}/project.yml"

# ---------------------------------------------------------------------------
# apply_and_verify <file> <label> <count-pattern> <count-pattern-for-value>
#                  <sed-expression>
#
# Prints the denominator on every step, so a zero match is a harness failure
# rather than a silent pass, and asserts the post-state can actually disagree:
#   - before > 0            (the matcher can see its subject at all)
#   - after_total == before  (no declaration was lost or duplicated)
#   - after_at_value == before (EVERY declaration now carries the new value)
# The last assertion is the one that matters: it is a statement about the whole
# file, not about the lines the substitution happened to touch.
# ---------------------------------------------------------------------------
apply_and_verify() {
  av_file=$1
  av_label=$2
  av_pat_any=$3
  av_pat_value=$4
  av_sed=$5

  if [ ! -f "$av_file" ]; then
    log "REFUSE: $av_label not found at $av_file"
    exit 1
  fi

  av_before=$(grep -c "$av_pat_any" "$av_file" || true)
  if [ "$av_before" -eq 0 ]; then
    log "REFUSE: $av_label declares CURRENT_PROJECT_VERSION 0 times."
    log "        The matcher found nothing, so this is an instrument failure,"
    log "        not a clean pass. Pattern: $av_pat_any"
    exit 1
  fi

  sed "$av_sed" "$av_file" > "${av_file}.cpv.tmp"
  mv "${av_file}.cpv.tmp" "$av_file"

  av_total=$(grep -c "$av_pat_any" "$av_file" || true)
  av_at_value=$(grep -c "$av_pat_value" "$av_file" || true)

  log "$av_label: $av_at_value of $av_total declarations at $BUILD_NUMBER (was $av_before declarations)"

  if [ "$av_total" -ne "$av_before" ]; then
    log "REFUSE: $av_label declaration count changed $av_before -> $av_total."
    exit 1
  fi
  if [ "$av_at_value" -ne "$av_before" ]; then
    log "REFUSE: $av_label has $av_at_value of $av_before declarations at"
    log "        $BUILD_NUMBER. Every one must match or the app and the widget"
    log "        extension can ship different build numbers."
    exit 1
  fi
}

apply_and_verify \
  "$PBXPROJ" \
  "project.pbxproj" \
  '^[[:space:]]*CURRENT_PROJECT_VERSION = [0-9][0-9]*;' \
  "^[[:space:]]*CURRENT_PROJECT_VERSION = ${BUILD_NUMBER};" \
  "s/^\\([[:space:]]*CURRENT_PROJECT_VERSION = \\)[0-9][0-9]*;/\\1${BUILD_NUMBER};/"

apply_and_verify \
  "$PROJECT_YML" \
  "project.yml" \
  '^[[:space:]]*CURRENT_PROJECT_VERSION: "[0-9][0-9]*"' \
  "^[[:space:]]*CURRENT_PROJECT_VERSION: \"${BUILD_NUMBER}\"" \
  "s/^\\([[:space:]]*CURRENT_PROJECT_VERSION: \\)\"[0-9][0-9]*\"/\\1\"${BUILD_NUMBER}\"/"

log "OK: CURRENT_PROJECT_VERSION set to $BUILD_NUMBER in both files."
exit 0
